language: node_js
before_install:
  - npm install -g greenkeeper-lockfile@1
  - npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run lint
  - npm run stylelint
  - npm run build
  - npm run coverage
after_script:
  - greenkeeper-lockfile-upload
