# Global settings applied to the whole site.  
# 
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  publish = "dist"
  
# Production context: All deploys to the main
# repository branch will inherit these settings.

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = '''
      echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test \
      sudo apt-get update \
      sudo apt-get install gcc-5 g++-5 \
      sudo rm /usr/bin/g++ \
      sudo ln -s /usr/bin/g++-5 /usr/bin/g++ \
      npm run build'''

[context.testing]
  command = '''
      echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test \
      sudo apt-get update \
      sudo apt-get install gcc-5 g++-5 \
      sudo rm /usr/bin/g++ \
      sudo ln -s /usr/bin/g++-5 /usr/bin/g++ \
      npm run build'''

[context.branch-deploy]
  command = '''
      echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test \
      sudo apt-get update \
      sudo apt-get install gcc-5 g++-5 \
      sudo rm /usr/bin/g++ \
      sudo ln -s /usr/bin/g++-5 /usr/bin/g++ \
      npm run build'''