# Global settings applied to the whole site.

[build]
  publish = "dist"
  
[context.deploy-preview]
  command = "npm run build"

[context.testing]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"