# Global settings applied to the whole site.  
# 
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  publish = "dist"
  
# Production context: All deploys to the main
# repository branch will inherit these settings.

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "npm run build:qaRegtest"

[context.testing]
  command = "npm run build:qaRegtest"

[context.branch-deploy]
  command = "npm run build:qaRegtest"

[context.production.environment]
  API_URL= "https://api.explorer.po.et"
  DATE_FORMAT= "MMMM Do YYYY"
  FROST_API_URL= "https://api.frost.po.et"

[context.deploy-preview.environment]
  API_URL= "https://testnet.qa.poetnetwork.net"
  DATE_FORMAT= "MMMM Do YYYY"
  FROST_API_URL= "https://frost-api.qa.poetnetwork.net"