export class Images {
  static readonly Avatar = require('./avatar.svg')
  static readonly Logo = require('./logo.svg')
  static readonly InvertedLogo = require('./logo-inverted.svg')
  static readonly Twitter = require('./twitter.svg')
  static readonly Github = require('./github.svg')
  static readonly Reddit = require('./reddit.svg')
  static readonly Glass = require('./glass.svg')
  static readonly Quill = require('./quill.svg')
  static readonly QuillInverted = require('./quill-inverted.svg')
  static readonly Calendar = require('./calendar.svg')
  static readonly Facebook = require('./facebook.svg')
  static readonly Twitter2 = require('./twitter2.svg')
  static readonly Google = require('./google.svg')
}
