// All unit test files should be imported here. For example,
// import '../../src/foo.test'
import '../../src/components/atoms/Button/Button.test'
import '../../src/components/atoms/Input/Input.test'
import '../../src/components/molecules/Form/Form.test'
import '../../src/reducers/LoadingPage.test'
import '../../src/reducers/Profile.test'
import '../../src/reducers/SignIn.test'
import '../../src/reducers/SignUp.test'
import '../../src/reducers/User.test'
import '../../src/sagas/GetProfile.test'
import '../../src/sagas/SignIn.test'
import '../../src/sagas/SignUp.test'
import '../../src/selectors/fetch.test'